version: '3' # version of docker-compose we are trying to use with this formatted file right now
services: # like saying "build these containers" not actual containers though, kinda a type of container
  redis-server: # first container to build
    image: 'redis' # use redis image
  node-app: # second container to build
    build: . #use dockerfile in current directory
    ports: # specify ports to map
      - "4001:8081" # a - in a .yml (yamel) file is how we specify an array